# Board pin constraints for my_cpu.
# Pin data follows project2/docs/xdc_constraints_reference.md.

set_property -dict {PACKAGE_PIN AD12 IOSTANDARD DIFF_HSTL_II_18} [get_ports i_sys_clk_p]
set_property -dict {PACKAGE_PIN AD11 IOSTANDARD DIFF_HSTL_II_18} [get_ports i_sys_clk_n]

set_property -dict {PACKAGE_PIN D18 IOSTANDARD LVCMOS33} [get_ports uart_rx]
set_property -dict {PACKAGE_PIN D17 IOSTANDARD LVCMOS33} [get_ports uart_tx]
set_property PULLUP true [get_ports uart_rx]

set_property -dict {PACKAGE_PIN B27 IOSTANDARD LVCMOS18} [get_ports {led[31]}]
set_property -dict {PACKAGE_PIN A27 IOSTANDARD LVCMOS18} [get_ports {led[30]}]
set_property -dict {PACKAGE_PIN A26 IOSTANDARD LVCMOS18} [get_ports {led[29]}]
set_property -dict {PACKAGE_PIN B25 IOSTANDARD LVCMOS18} [get_ports {led[28]}]
set_property -dict {PACKAGE_PIN A25 IOSTANDARD LVCMOS18} [get_ports {led[27]}]
set_property -dict {PACKAGE_PIN B24 IOSTANDARD LVCMOS18} [get_ports {led[26]}]
set_property -dict {PACKAGE_PIN B23 IOSTANDARD LVCMOS18} [get_ports {led[25]}]
set_property -dict {PACKAGE_PIN A23 IOSTANDARD LVCMOS18} [get_ports {led[24]}]
set_property -dict {PACKAGE_PIN E30 IOSTANDARD LVCMOS18} [get_ports {led[23]}]
set_property -dict {PACKAGE_PIN C30 IOSTANDARD LVCMOS18} [get_ports {led[22]}]
set_property -dict {PACKAGE_PIN D28 IOSTANDARD LVCMOS18} [get_ports {led[21]}]
set_property -dict {PACKAGE_PIN E26 IOSTANDARD LVCMOS18} [get_ports {led[20]}]
set_property -dict {PACKAGE_PIN F25 IOSTANDARD LVCMOS18} [get_ports {led[19]}]
set_property -dict {PACKAGE_PIN D23 IOSTANDARD LVCMOS18} [get_ports {led[18]}]
set_property -dict {PACKAGE_PIN F23 IOSTANDARD LVCMOS18} [get_ports {led[17]}]
set_property -dict {PACKAGE_PIN F12 IOSTANDARD LVCMOS18} [get_ports {led[16]}]
set_property -dict {PACKAGE_PIN G28 IOSTANDARD LVCMOS18} [get_ports {led[15]}]
set_property -dict {PACKAGE_PIN E28 IOSTANDARD LVCMOS18} [get_ports {led[14]}]
set_property -dict {PACKAGE_PIN C29 IOSTANDARD LVCMOS18} [get_ports {led[13]}]
set_property -dict {PACKAGE_PIN D26 IOSTANDARD LVCMOS18} [get_ports {led[12]}]
set_property -dict {PACKAGE_PIN C25 IOSTANDARD LVCMOS18} [get_ports {led[11]}]
set_property -dict {PACKAGE_PIN D24 IOSTANDARD LVCMOS18} [get_ports {led[10]}]
set_property -dict {PACKAGE_PIN E23 IOSTANDARD LVCMOS18} [get_ports {led[9]}]
set_property -dict {PACKAGE_PIN G23 IOSTANDARD LVCMOS18} [get_ports {led[8]}]
set_property -dict {PACKAGE_PIN E29 IOSTANDARD LVCMOS18} [get_ports {led[7]}]
set_property -dict {PACKAGE_PIN G25 IOSTANDARD LVCMOS18} [get_ports {led[6]}]
set_property -dict {PACKAGE_PIN F26 IOSTANDARD LVCMOS18} [get_ports {led[5]}]
set_property -dict {PACKAGE_PIN C26 IOSTANDARD LVCMOS18} [get_ports {led[4]}]
set_property -dict {PACKAGE_PIN E25 IOSTANDARD LVCMOS18} [get_ports {led[3]}]
set_property -dict {PACKAGE_PIN C24 IOSTANDARD LVCMOS18} [get_ports {led[2]}]
set_property -dict {PACKAGE_PIN E24 IOSTANDARD LVCMOS18} [get_ports {led[1]}]
set_property -dict {PACKAGE_PIN G24 IOSTANDARD LVCMOS18} [get_ports {led[0]}]
