@echo off
setlocal EnableExtensions EnableDelayedExpansion

rem ============================================================
rem USER EDIT AREA - change the values in this block when needed
rem ============================================================
rem [EDIT 1] Source initialization files.
rem          SOURCE_INST_COE is used when TARGET_MEMORY is inst or both.
rem          SOURCE_DATA_COE is used when TARGET_MEMORY is data or both.
set "SOURCE_INST_COE=F:\graduation_project\project2\board_tests\05_coremark\output\inst.coe"
set "SOURCE_DATA_COE=F:\graduation_project\project2\board_tests\05_coremark\output\data.coe"

rem [EDIT 2] Base bitstream and MMI generated by the current Vivado implementation.
rem          These two files must come from the same implementation result.
rem          After the first byte-bank rebuild, this fast-update base is created
rem          automatically and can be reused for second-level COE replacement.
set "BASE_BIT=%~dp0project-vivado\my_cpu_fast_update_base.bit"
set "MMI_FILE=%~dp0project-vivado\riscv-graduation.runs\impl_1\my_cpu.mmi"

rem [EDIT 3] Final bitstream output directory and file name.
set "OUTPUT_BIT_DIR=%~dp0project-vivado"
set "OUTPUT_BIT_NAME=coremark_update.bit"

rem [EDIT 4] Select memory to update: inst, data, or both.
rem          inst updates u_inst_ram; data updates u_data_ram; both updates both.
set "TARGET_MEMORY=both"

rem [EDIT 5] Update method: auto, updatemem, or rebuild.
rem          auto uses fast updatemem when the current MMI has data byte banks.
rem          If the byte-bank base does not exist yet, auto performs one rebuild.
set "UPDATE_METHOD=auto"

rem [EDIT 6 optional] Vivado/updatemem executables, only needed when they are not in PATH.
rem set "VIVADO_BIN=F:\Xilinx\Vivado\2023.2\bin\vivado.bat"
rem set "UPDATEMEM_BIN=F:\Xilinx\Vivado\2023.2\bin\updatemem.bat"

rem ============================================================
rem Command line overrides
rem ============================================================
rem Usage:
rem   update_init_from_coe.bat
rem   update_init_from_coe.bat inst.coe
rem   update_init_from_coe.bat inst.coe output.bit
rem   update_init_from_coe.bat inst.coe output.bit base.bit mmi_file
rem   update_init_from_coe.bat inst.coe output.bit base.bit mmi_file data.coe

if /I "%~1"=="/?" goto :usage
if /I "%~1"=="-h" goto :usage
if /I "%~1"=="--help" goto :usage

if not "%~1"=="" set "SOURCE_INST_COE=%~1"

if not "%~2"=="" (
    if "%~dp2"=="" (
        set "OUTPUT_BIT_NAME=%~2"
    ) else (
        set "OUTPUT_BIT_DIR=%~dp2"
        set "OUTPUT_BIT_NAME=%~nx2"
    )
)

if not "%~3"=="" set "BASE_BIT=%~3"
if not "%~4"=="" set "MMI_FILE=%~4"
if not "%~5"=="" set "SOURCE_DATA_COE=%~5"

rem ============================================================
rem Derived paths
rem ============================================================
set "SCRIPT_DIR=%~dp0"
set "CONVERT_SCRIPT=%SCRIPT_DIR%docs\mem_tools\convert_to_mem.py"
set "UPDATEMEM_TCL=%SCRIPT_DIR%docs\mem_tools\scriptsupdate_mem.tcl"
set "REBUILD_TCL=%SCRIPT_DIR%docs\mem_tools\rebuild_bitstream_with_mem.tcl"
set "WORK_DIR=%SCRIPT_DIR%build\mem_update"
set "PROJECT_XPR=%SCRIPT_DIR%project-vivado\riscv-graduation.xpr"

for %%D in ("%OUTPUT_BIT_DIR%") do set "OUTPUT_BIT_DIR=%%~fD"
set "FINAL_OUT_BIT=%OUTPUT_BIT_DIR%\%OUTPUT_BIT_NAME%"
set "ORIGINAL_BASE_BIT=%BASE_BIT%"

for %%F in ("%SOURCE_INST_COE%") do set "INST_MEM_FILE=%WORK_DIR%\%%~nF_inst.mem"
for %%F in ("%SOURCE_DATA_COE%") do set "DATA_MEM_FILE=%WORK_DIR%\%%~nF_data.mem"
for %%F in ("%SOURCE_DATA_COE%") do set "DATA_MEM_FILE_0=%WORK_DIR%\%%~nF_data_b0.mem"
for %%F in ("%SOURCE_DATA_COE%") do set "DATA_MEM_FILE_1=%WORK_DIR%\%%~nF_data_b1.mem"
for %%F in ("%SOURCE_DATA_COE%") do set "DATA_MEM_FILE_2=%WORK_DIR%\%%~nF_data_b2.mem"
for %%F in ("%SOURCE_DATA_COE%") do set "DATA_MEM_FILE_3=%WORK_DIR%\%%~nF_data_b3.mem"
for %%F in ("%SOURCE_DATA_COE%") do set "DATA_CHUNK_PREFIX=%%~nF_data"
set "DATA_CHUNK_DIR=%WORK_DIR%"
set "TEMP_INST_BIT=%WORK_DIR%\_after_inst_update.bit"
set "FAST_BASE_BIT=%SCRIPT_DIR%project-vivado\my_cpu_fast_update_base.bit"

if /I "%TARGET_MEMORY%"=="inst" (
    set "DO_INST=1"
    set "DO_DATA=0"
) else if /I "%TARGET_MEMORY%"=="data" (
    set "DO_INST=0"
    set "DO_DATA=1"
) else if /I "%TARGET_MEMORY%"=="both" (
    set "DO_INST=1"
    set "DO_DATA=1"
) else (
    echo ERROR: TARGET_MEMORY must be inst, data, or both. Current: %TARGET_MEMORY%
    exit /b 1
)

rem ============================================================
rem Checks
rem ============================================================
if "%DO_INST%"=="1" (
    if not exist "%SOURCE_INST_COE%" (
        echo ERROR: instruction source COE/HEX file not found:
        echo   %SOURCE_INST_COE%
        echo.
        echo Edit SOURCE_INST_COE near the top of this .bat file, or pass it as arg1.
        exit /b 1
    )
)

if "%DO_DATA%"=="1" (
    if not exist "%SOURCE_DATA_COE%" (
        echo ERROR: data source COE/HEX file not found:
        echo   %SOURCE_DATA_COE%
        echo.
        echo Edit SOURCE_DATA_COE near the top of this .bat file, or pass it as arg5.
        exit /b 1
    )
)

set "BASE_BIT_MISSING=0"
if not exist "%BASE_BIT%" set "BASE_BIT_MISSING=1"

set "MMI_FILE_MISSING=0"
if not exist "%MMI_FILE%" set "MMI_FILE_MISSING=1"

if not exist "%CONVERT_SCRIPT%" (
    echo ERROR: converter not found:
    echo   %CONVERT_SCRIPT%
    exit /b 1
)

if not exist "%REBUILD_TCL%" (
    echo ERROR: rebuild Tcl not found:
    echo   %REBUILD_TCL%
    exit /b 1
)

if not exist "%WORK_DIR%" mkdir "%WORK_DIR%" >nul 2>nul
if not exist "%OUTPUT_BIT_DIR%" mkdir "%OUTPUT_BIT_DIR%" >nul 2>nul

call :find_python
if errorlevel 1 exit /b 1

if not defined VIVADO_BIN call :find_vivado
if not defined UPDATEMEM_BIN call :find_updatemem

rem ============================================================
rem Convert COE/HEX to MEM
rem ============================================================
if "%DO_INST%"=="1" (
    echo.
    echo === Convert instruction initialization file ===
    echo Source : %SOURCE_INST_COE%
    echo MEM    : %INST_MEM_FILE%
    %PYTHON_CMD% "%CONVERT_SCRIPT%" "%SOURCE_INST_COE%" "%INST_MEM_FILE%"
    if errorlevel 1 (
        echo ERROR: failed to convert instruction source file to MEM.
        exit /b 1
    )
)

if "%DO_DATA%"=="1" (
    echo.
    echo === Convert data initialization file ===
    echo Source : %SOURCE_DATA_COE%
    echo MEM    : %DATA_MEM_FILE%
    echo Chunks : %DATA_CHUNK_DIR%\%DATA_CHUNK_PREFIX%_chunk00.mem ... chunk15.mem
    %PYTHON_CMD% "%CONVERT_SCRIPT%" "%SOURCE_DATA_COE%" "%DATA_MEM_FILE%" --word-chunks "%DATA_CHUNK_DIR%" "%DATA_CHUNK_PREFIX%"
    if errorlevel 1 (
        echo ERROR: failed to convert data source file to MEM.
        exit /b 1
    )
)

set "DATA_FAST_LAYOUT=0"
if "%MMI_FILE_MISSING%"=="0" (
    findstr /C:"u_data_ram/u_data_chunk0/u_xpm_data_ram/xpm_memory_base_inst" "%MMI_FILE%" >nul 2>nul
    if not errorlevel 1 set "DATA_FAST_LAYOUT=1"
)

set "RUN_METHOD=%UPDATE_METHOD%"
if /I "%RUN_METHOD%"=="auto" (
    if "%DO_DATA%"=="1" (
        if "%DATA_FAST_LAYOUT%"=="1" (
            if "%BASE_BIT_MISSING%"=="0" (
                set "RUN_METHOD=updatemem"
            ) else (
                set "RUN_METHOD=rebuild"
            )
        ) else (
            set "RUN_METHOD=rebuild"
        )
    ) else (
        set "RUN_METHOD=updatemem"
    )
)

if /I not "%RUN_METHOD%"=="updatemem" if /I not "%RUN_METHOD%"=="rebuild" (
    echo ERROR: UPDATE_METHOD must be auto, updatemem, or rebuild. Current: %UPDATE_METHOD%
    exit /b 1
)

if /I "%RUN_METHOD%"=="updatemem" (
    if "%BASE_BIT_MISSING%"=="1" (
        echo ERROR: base bitstream not found:
        echo   %BASE_BIT%
        echo.
        echo Run once with UPDATE_METHOD=rebuild, or keep UPDATE_METHOD=auto with TARGET_MEMORY=both.
        exit /b 1
    )
    if "%MMI_FILE_MISSING%"=="1" (
        echo ERROR: MMI file not found:
        echo   %MMI_FILE%
        echo.
        echo The MMI must come from the same implementation as BASE_BIT.
        exit /b 1
    )
    if "%DO_DATA%"=="1" if not "%DATA_FAST_LAYOUT%"=="1" (
        echo ERROR: current MMI does not contain data byte-bank memories.
        echo   %MMI_FILE%
        echo.
        echo Run once with UPDATE_METHOD=rebuild to generate a fast-update base bit/MMI.
        exit /b 1
    )
)

if /I "%RUN_METHOD%"=="rebuild" goto :rebuild_bitstream

:run_updatemem
rem ============================================================
rem Replace BRAM contents in bitstream
rem ============================================================
echo.
echo === Update bitstream memory contents ===
echo Base BIT : %BASE_BIT%
echo MMI      : %MMI_FILE%
echo Target   : %TARGET_MEMORY%
echo Output   : %FINAL_OUT_BIT%

set "MMI_FILE=%MMI_FILE%"

if "%DO_INST%"=="1" if "%DO_DATA%"=="1" (
    set "INST_OUT_BIT=%TEMP_INST_BIT%"
) else (
    set "INST_OUT_BIT=%FINAL_OUT_BIT%"
)

if "%DO_INST%"=="1" (
    call :update_one_memory "%ORIGINAL_BASE_BIT%" "%INST_MEM_FILE%" "%INST_OUT_BIT%" "u_inst_ram/u_xpm_inst_rom/xpm_memory_base_inst" "instruction ROM"
    if errorlevel 1 exit /b 1
)

if "%DO_DATA%"=="1" (
    echo.
    echo --- Update data RAM word chunks ---
    if "%DO_INST%"=="1" (
        set "DATA_BASE_BIT=%TEMP_INST_BIT%"
    ) else (
        set "DATA_BASE_BIT=%ORIGINAL_BASE_BIT%"
    )

    for /L %%C in (0,1,15) do (
        set "CHUNK_NUM=0%%C"
        set "CHUNK_NUM=!CHUNK_NUM:~-2!"
        set "CHUNK_MEM=%DATA_CHUNK_DIR%\%DATA_CHUNK_PREFIX%_chunk!CHUNK_NUM!.mem"
        if %%C==15 (
            set "CHUNK_OUT=%FINAL_OUT_BIT%"
        ) else (
            set /A NEXT_C=%%C+1
            set "NEXT_NUM=0!NEXT_C!"
            set "NEXT_NUM=!NEXT_NUM:~-2!"
            set "CHUNK_OUT=%WORK_DIR%\_after_data_chunk!NEXT_NUM!.bit"
        )
        call :update_one_memory "!DATA_BASE_BIT!" "!CHUNK_MEM!" "!CHUNK_OUT!" "u_data_ram/u_data_chunk%%C/u_xpm_data_ram/xpm_memory_base_inst" "data RAM chunk %%C"
        if errorlevel 1 exit /b 1
        set "DATA_BASE_BIT=!CHUNK_OUT!"
    )
)

if not exist "%FINAL_OUT_BIT%" (
    echo ERROR: Vivado finished, but output bit was not found:
    echo   %FINAL_OUT_BIT%
    exit /b 1
)

echo.
echo DONE.
echo Generated bitstream:
echo   %FINAL_OUT_BIT%
exit /b 0

:update_one_memory
set "BASE_BIT=%~1"
set "MEM_FILE=%~2"
set "OUT_BIT=%~3"
set "PROC_PATH=%~4"
set "UPDATE_LABEL=%~5"
echo.
echo --- Update %UPDATE_LABEL% ---
echo Base BIT : %BASE_BIT%
echo MEM      : %MEM_FILE%
echo OUT BIT  : %OUT_BIT%
echo ProcPath : %PROC_PATH%
call "%UPDATEMEM_BIN%" -force -meminfo "%MMI_FILE%" -data "%MEM_FILE%" -bit "%BASE_BIT%" -proc "%PROC_PATH%" -out "%OUT_BIT%"
if errorlevel 1 (
    echo ERROR: Vivado updatemem failed for %UPDATE_LABEL%.
    exit /b 1
)
if not exist "%OUT_BIT%" (
    echo ERROR: updatemem did not generate output bit for %UPDATE_LABEL%.
    echo   Expected: %OUT_BIT%
    exit /b 1
)
exit /b 0

:rebuild_bitstream
echo.
echo === Rebuild bitstream with converted MEM files ===
echo Project  : %PROJECT_XPR%
echo Inst MEM : %INST_MEM_FILE%
echo Data MEM : %DATA_MEM_FILE%
echo Chunks   : %DATA_CHUNK_DIR%\%DATA_CHUNK_PREFIX%_chunk00.mem ... chunk15.mem
echo Output   : %FINAL_OUT_BIT%

if not exist "%INST_MEM_FILE%" (
    echo ERROR: rebuild method requires instruction MEM file:
    echo   %INST_MEM_FILE%
    exit /b 1
)

if not exist "%DATA_MEM_FILE%" (
    echo ERROR: rebuild method requires data MEM file:
    echo   %DATA_MEM_FILE%
    exit /b 1
)

if not exist "%DATA_CHUNK_DIR%\%DATA_CHUNK_PREFIX%_chunk00.mem" (
    echo ERROR: rebuild method requires data word chunk MEM files.
    exit /b 1
)
if not exist "%DATA_CHUNK_DIR%\%DATA_CHUNK_PREFIX%_chunk15.mem" (
    echo ERROR: rebuild method requires data word chunk MEM files.
    exit /b 1
)

set "PROJECT_XPR=%PROJECT_XPR%"
set "INST_MEM_FILE=%INST_MEM_FILE%"
set "DATA_MEM_FILE=%DATA_MEM_FILE%"
set "OUT_BIT=%FINAL_OUT_BIT%"

call "%VIVADO_BIN%" -mode batch -source "%REBUILD_TCL%"
if errorlevel 1 (
    echo ERROR: Vivado rebuild failed.
    exit /b 1
)

if not exist "%FINAL_OUT_BIT%" (
    echo ERROR: Vivado finished, but output bit was not found:
    echo   %FINAL_OUT_BIT%
    exit /b 1
)

echo.
echo DONE.
echo Generated bitstream:
echo   %FINAL_OUT_BIT%
copy /y "%FINAL_OUT_BIT%" "%FAST_BASE_BIT%" >nul 2>nul
if not errorlevel 1 (
    echo Fast-update base bitstream:
    echo   %FAST_BASE_BIT%
)
if /I "%UPDATE_METHOD%"=="auto" if "%DO_DATA%"=="1" (
    echo.
    echo === Rebuild finished; now applying fast chunk update ===
    set "BASE_BIT=%FAST_BASE_BIT%"
    set "ORIGINAL_BASE_BIT=%FAST_BASE_BIT%"
    set "BASE_BIT_MISSING=0"
    set "MMI_FILE_MISSING=0"
    set "DATA_FAST_LAYOUT=1"
    goto :run_updatemem
)
exit /b 0

:find_python
where py >nul 2>nul
if not errorlevel 1 (
    set "PYTHON_CMD=py -3"
    exit /b 0
)

where python >nul 2>nul
if not errorlevel 1 (
    set "PYTHON_CMD=python"
    exit /b 0
)

echo ERROR: Python was not found. Add py/python to PATH.
exit /b 1

:find_vivado
where vivado >nul 2>nul
if not errorlevel 1 (
    set "VIVADO_BIN=vivado"
    exit /b 0
)

for %%D in (C D E F) do (
    for /d %%V in ("%%D:\Xilinx\Vivado\*") do (
        if exist "%%~fV\bin\vivado.bat" (
            set "VIVADO_BIN=%%~fV\bin\vivado.bat"
            exit /b 0
        )
    )
)

set "VIVADO_BIN=vivado"
exit /b 0

:find_updatemem
if defined VIVADO_BIN (
    for %%V in ("%VIVADO_BIN%") do (
        if exist "%%~dpVupdatemem.bat" (
            set "UPDATEMEM_BIN=%%~dpVupdatemem.bat"
            exit /b 0
        )
        if exist "%%~dpVupdatemem" (
            set "UPDATEMEM_BIN=%%~dpVupdatemem"
            exit /b 0
        )
    )
)

where updatemem.bat >nul 2>nul
if not errorlevel 1 (
    set "UPDATEMEM_BIN=updatemem.bat"
    exit /b 0
)

where updatemem >nul 2>nul
if not errorlevel 1 (
    set "UPDATEMEM_BIN=updatemem"
    exit /b 0
)

for %%D in (C D E F) do (
    for /d %%V in ("%%D:\Xilinx\Vivado\*") do (
        if exist "%%~fV\bin\updatemem.bat" (
            set "UPDATEMEM_BIN=%%~fV\bin\updatemem.bat"
            exit /b 0
        )
    )
)

echo ERROR: updatemem was not found. Set UPDATEMEM_BIN near the top of this script.
exit /b 1

:usage
echo Usage:
echo   %~nx0
echo   %~nx0 inst.coe
echo   %~nx0 inst.coe output.bit
echo   %~nx0 inst.coe output.bit base.bit mmi_file
echo   %~nx0 inst.coe output.bit base.bit mmi_file data.coe
echo.
echo Edit these variables near the top of the script:
echo   SOURCE_INST_COE  instruction .coe/.hex path
echo   SOURCE_DATA_COE  data .coe/.hex path
echo   OUTPUT_BIT_DIR   output bit directory
echo   OUTPUT_BIT_NAME  output bit file name
echo   BASE_BIT         base bitstream generated by Vivado
echo   MMI_FILE         MMI file generated with the matching bitstream
echo   TARGET_MEMORY    inst, data, or both
echo   UPDATE_METHOD    auto, updatemem, or rebuild
echo   VIVADO_BIN       optional path to vivado.bat
echo   UPDATEMEM_BIN    optional path to updatemem.bat
exit /b 0
